Prevent concurrent runs of launch queue management
This ensures that the compute queue actions are processed in the correct
order.

diff --git a/launch/launch-queue-management/package/data/etc/handlers/launch-queue-management/event-periodic b/launch/launch-queue-management/package/data/etc/handlers/launch-queue-management/event-periodic
--- a/launch/launch-queue-management/package/data/etc/handlers/launch-queue-management/event-periodic
+++ b/launch/launch-queue-management/package/data/etc/handlers/launch-queue-management/event-periodic
@@ -81,19 +81,26 @@ _queues_endpoint() {
 }
 
 main() {
-  _queues_load_personality
-  local auth_user
-  files_load_config instance config/cluster
-  if [ "${cw_INSTANCE_role}" != "master" ]; then
-      return 0
-  fi
+    files_load_config instance config/cluster
+    if [ "${cw_INSTANCE_role}" != "master" ]; then
+        return 0
+    fi
 
-  auth_user=$(_queues_cluster_uuid)
-  ruby_exec "$(handler_dir)/share/queue-manager.rb" \
-      "${_ALCES}" \
-      "$(_queues_endpoint)" \
-      "$(auth_user)" \
-      "$(_queues_auth_password)"
+    if files_lock "launch-queue-management"; then
+        trap files_unlock EXIT
+        _queues_load_personality
+        local auth_user
+
+        auth_user=$(_queues_cluster_uuid)
+        ruby_exec "$(handler_dir)/share/queue-manager.rb" \
+            "${_ALCES}" \
+            "$(_queues_endpoint)" \
+            "$(auth_user)" \
+            "$(_queues_auth_password)"
+    else
+        echo "Locking failed; unable to process launch compute actions queue"
+        return 1
+    fi
 }
 
 setup
